---
- name: Signal role
  tags:
    - signal
  block:

  # apt
  - ansible.builtin.import_tasks: install_apt.yml
  # desktop
  - ansible.builtin.import_tasks: desktop.yml
  # systemd user
  - ansible.builtin.import_tasks: systemd_user.yml